version: "3.7"
services:
  service1:
    image: service1 
    build:
      context: /home/student/NBSMentoredChallenge/service-1/
      dockerfile: Dockerfile
    ports:
    - target: 5000
      published: 5000
      protocol: tcp
  service2:
    image: service2
    build:
      context: /home/student/NBSMentoredChallenge/service-2/
      dockerfile: Dockerfile
    ports:
    - target: 5001
      published: 5001
      protocol: tcp
  service3:
    image: service3
    build:
      context: /home/student/NBSMentoredChallenge/service-3/
      dockerfile: Dockerfile
    ports:
    - target: 5002
      published: 5002
      protocol: tcp
  service4:
    image: service4
    build:
      context: /home/student/NBSMentoredChallenge/service-4/
      dockerfile: Dockerfile
    ports:
    - target: 5003
      published: 5003
      protocol: tcp
