- hosts: 127.0.0.1
  connection: local
  become: true
  tasks:
    - name: 'Install Testing Python requirements'
      pip:
        requirements: /home/student/TDP_Mentor_Project/docker/PythonRequirements.txt
    - name: 'install docker dependencies'
      apt:
        pkg:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
      state: latest
      update_cache: true
  - name: 'Add docker GPG apt key'
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present
  - name: 'add docker repository'
    apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable
      state: present
  - name: 'update and install docker-ce'
    apt:
      name: docker-ce
      state: latest
      update_cache: true
  - name: 'install docker module for python'
    pip:
      name: docker
~                     
